### ISSUE TITLE
Proposal: Remove "dev-start" magic from "make bash" command

### ISSUE THREAD

**Issue by resdntalien** [manifoldai/orbyter-cookiecutter#53]
there is conflicts that occur when we have separate compose files for cloud and local.

**Comment by rameshvs** [comment]
I wonder if a better solution might be to have the `make dev-X`  commands be smarter, so that they use the right compose file depending on whether you're working locally or in the cloud. Is there an environment variable that's already set differently between local/cloud dev setups? If so, we can use that to decide whether the default compose file should be `docker-compose.yml` or `docker-compose-cloud.yml`.
